# Generated by Django 2.2.6 on 2019-11-05 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_day', models.CharField(max_length=50)),
                ('end_day', models.CharField(max_length=50)),
                ('xn', models.CharField(max_length=50)),
                ('xq', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=1)),
                ('news', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
