# Generated by Django 2.2.6 on 2019-11-05 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OUC', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-date',)},
        ),
    ]
