# Generated by Django 2.2.6 on 2019-11-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OUC', '0004_auto_20191120_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swiper',
            name='image',
            field=models.ImageField(upload_to='./OUC/static/upload_image/20191120'),
        ),
    ]
