# Generated by Django 2.2.6 on 2020-01-07 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OUC', '0006_auto_20200107_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swiper',
            name='image',
            field=models.ImageField(upload_to='./OUC/static/upload_image/'),
        ),
    ]
