# Generated by Django 2.2.6 on 2020-12-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OUC', '0007_auto_20200107_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sno', models.CharField(db_index=True, default='123', max_length=15, verbose_name='学号')),
                ('passwd', models.CharField(default='123', max_length=20, verbose_name='密码')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='最新登录日期')),
                ('first_login_date', models.DateTimeField(auto_now_add=True, verbose_name='登录日期')),
            ],
            options={
                'ordering': ('-update_date',),
            },
        ),
    ]
