# Generated by Django 2.2.6 on 2020-12-16 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OUC', '0008_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='first_login_date',
            new_name='login_date',
        ),
    ]
