# Generated by Django 2.2.6 on 2020-12-16 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OUC', '0009_auto_20201216_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='login_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='注册日期'),
        ),
    ]
