# Generated by Django 2.2.6 on 2020-12-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OUC', '0010_auto_20201216_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(default='-', max_length=20, verbose_name='学院'),
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='-', max_length=20, verbose_name='姓名'),
        ),
        migrations.AddField(
            model_name='student',
            name='profession',
            field=models.CharField(default='-', max_length=40, verbose_name='专业'),
        ),
        migrations.AddField(
            model_name='student',
            name='research',
            field=models.CharField(default='-', max_length=40, verbose_name='研究方向'),
        ),
        migrations.AddField(
            model_name='student',
            name='supervisor',
            field=models.CharField(default='-', max_length=20, verbose_name='导师'),
        ),
        migrations.AlterField(
            model_name='config',
            name='begin_day',
            field=models.CharField(max_length=50, verbose_name='开始日期(如2020-08-24 00:00:00)'),
        ),
        migrations.AlterField(
            model_name='config',
            name='end_day',
            field=models.CharField(max_length=50, verbose_name='结束日期(如2021-01-26 00:00:00)'),
        ),
        migrations.AlterField(
            model_name='config',
            name='xn',
            field=models.CharField(max_length=50, verbose_name='学年(如2020)'),
        ),
        migrations.AlterField(
            model_name='config',
            name='xq',
            field=models.CharField(max_length=50, verbose_name='学期(如2020-2021夏秋)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='passwd',
            field=models.CharField(default='-', max_length=20, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sno',
            field=models.CharField(db_index=True, default='-', max_length=15, verbose_name='学号'),
        ),
    ]
