# Generated by Django 2.2.6 on 2020-12-17 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OUC', '0011_auto_20201216_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='openid',
            field=models.CharField(db_index=True, default=1, max_length=50, verbose_name='openid'),
            preserve_default=False,
        ),
    ]
