# Generated by Django 2.2.6 on 2020-12-16 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OUC', '0006_auto_20191228_2138'),
        ('OUC', '0011_auto_20201216_1925'),
    ]

    operations = [
    ]
