# Generated by Django 2.2.6 on 2020-12-17 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OUC', '0012_student_openid'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.IntegerField(default=0, verbose_name='用户状态(0:正常,1:问题,2:禁用)'),
        ),
    ]
