# Generated by Django 2.2.6 on 2020-12-17 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OUC', '0013_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='lock_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='禁用日期'),
        ),
    ]
