# Generated by Django 2.2.6 on 2020-12-17 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OUC', '0012_merge_20201216_2008'),
        ('OUC', '0014_student_lock_date'),
    ]

    operations = [
    ]
