# Generated by Django 2.2.6 on 2020-12-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OUC', '0015_auto_20201218_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribeStudent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('openid', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='openid')),
                ('sno', models.CharField(db_index=True, default='-', max_length=15, verbose_name='学号')),
                ('scores', models.CharField(default='', max_length=256, verbose_name='成绩')),
                ('status', models.IntegerField(default=0, verbose_name='是否订阅(1为订阅，0为没有)')),
                ('subscribe_date', models.DateTimeField(auto_now_add=True, verbose_name='订阅日期')),
            ],
        ),
    ]
