# Generated by Django 2.2.6 on 2020-12-21 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OUC', '0016_subscribestudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='is_open_subscribe',
            field=models.IntegerField(default=0, verbose_name='是否开启成绩通知(0:未开启,1:开启,2:只开启管理员的)'),
        ),
    ]
