# Generated by Django 2.2.6 on 2020-12-21 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OUC', '0017_config_is_open_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribestudent',
            name='send_fail_nums',
            field=models.IntegerField(default=0, verbose_name='发送失败次数'),
        ),
        migrations.AddField(
            model_name='subscribestudent',
            name='send_success_nums',
            field=models.IntegerField(default=0, verbose_name='发送成功次数'),
        ),
        migrations.AddField(
            model_name='subscribestudent',
            name='travel_nums',
            field=models.IntegerField(default=0, verbose_name='遍历次数'),
        ),
    ]
