# Generated by Django 2.2.6 on 2020-12-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OUC', '0018_auto_20201221_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribestudent',
            name='failure_popup',
            field=models.IntegerField(default=1, verbose_name='是否失效弹窗'),
        ),
    ]
