# Generated by Django 2.2.6 on 2020-12-21 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OUC', '0015_merge_20201217_1545'),
        ('OUC', '0020_auto_20201221_1620'),
    ]

    operations = [
    ]
