# Generated by Django 2.2.6 on 2021-01-07 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OUC', '0021_auto_20210107_1514'),
        ('OUC', '0021_merge_20201221_1650'),
    ]

    operations = [
    ]
