# Generated by Django 2.2.6 on 2021-01-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OUC', '0021_auto_20210107_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRank',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('openid', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='openid')),
                ('sno', models.CharField(db_index=True, default='-', max_length=15, verbose_name='学号')),
                ('avg_score', models.IntegerField(default=0, verbose_name='平均学分绩')),
                ('avg_score_update_date', models.DateTimeField(auto_now=True, verbose_name='学分绩更新日期')),
                ('department', models.CharField(default='-', max_length=20, verbose_name='学院')),
                ('profession', models.CharField(default='-', max_length=40, verbose_name='专业')),
                ('rank_profession', models.CharField(default='-', max_length=1024, verbose_name='参与排名的专业')),
                ('travel_nums', models.IntegerField(default=1, verbose_name='遍历次数')),
            ],
        ),
        migrations.AddField(
            model_name='config',
            name='is_open_score_rank',
            field=models.IntegerField(default=0, verbose_name='是否开启成绩排名遍历(0:未开启,1:开启,2:只开启管理员的)'),
        ),
        migrations.AddField(
            model_name='config',
            name='score_rank_max',
            field=models.CharField(default='2120', max_length=5, verbose_name='参与成绩计算的年级上限'),
        ),
        migrations.AddField(
            model_name='config',
            name='score_rank_min',
            field=models.CharField(default='2120', max_length=5, verbose_name='参与成绩计算的年级下限'),
        ),
    ]
