# Generated by Django 2.2.6 on 2021-01-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OUC', '0024_auto_20210122_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrank',
            name='avg_score',
            field=models.CharField(default='0', max_length=15, verbose_name='平均学分绩'),
        ),
    ]
