# Generated by Django 2.2.6 on 2021-01-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OUC', '0031_auto_20210122_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribestudent',
            name='scores',
            field=models.DecimalField(decimal_places=4, default='-', max_digits=7, verbose_name='成绩'),
        ),
    ]
