# Generated by Django 2.2.6 on 2021-01-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OUC', '0032_auto_20210122_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribestudent',
            name='scores',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7, verbose_name='成绩'),
        ),
    ]
