# Generated by Django 2.2.6 on 2021-01-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OUC', '0033_auto_20210122_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribestudent',
            name='scores',
            field=models.CharField(default='-', max_length=256, verbose_name='成绩'),
        ),
    ]
