# Generated by Django 2.2.6 on 2021-01-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OUC', '0036_auto_20210122_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrank',
            name='travel_nums',
            field=models.IntegerField(default=0, verbose_name='遍历次数'),
        ),
    ]
