# Generated by Django 2.2.6 on 2021-01-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OUC', '0037_auto_20210122_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='is_open_score_rank',
        ),
        migrations.RemoveField(
            model_name='config',
            name='score_rank_max',
        ),
        migrations.RemoveField(
            model_name='config',
            name='score_rank_min',
        ),
        migrations.AddField(
            model_name='config',
            name='get_score_rank_nj_max',
            field=models.CharField(default='2120', max_length=5, verbose_name='参与成绩排名的年级上限'),
        ),
        migrations.AddField(
            model_name='config',
            name='get_score_rank_nj_min',
            field=models.CharField(default='2120', max_length=5, verbose_name='参与成绩排名的年级下限'),
        ),
        migrations.AddField(
            model_name='config',
            name='is_open_score_rank_travel',
            field=models.IntegerField(default=0, verbose_name='是否开启成绩排名的遍历(0:未开启,1:开启,2:只开启管理员的)'),
        ),
        migrations.AddField(
            model_name='config',
            name='score_rank_travel_nj_max',
            field=models.CharField(default='2120', max_length=5, verbose_name='成绩排名遍历的年级上限'),
        ),
        migrations.AddField(
            model_name='config',
            name='score_rank_travel_nj_min',
            field=models.CharField(default='2120', max_length=5, verbose_name='成绩排名遍历的年级下限'),
        ),
    ]
