# Generated by Django 2.2.6 on 2021-01-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OUC', '0038_auto_20210124_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrank',
            name='profession',
            field=models.CharField(db_index=True, default='-', max_length=40, verbose_name='专业'),
        ),
        migrations.AlterField(
            model_name='studentrank',
            name='department',
            field=models.CharField(db_index=True, default='-', max_length=20, verbose_name='学院'),
        ),
        migrations.AlterField(
            model_name='studentrank',
            name='research',
            field=models.CharField(db_index=True, default='-', max_length=40, verbose_name='研究方向'),
        ),
    ]
