# Generated by Django 2.2.6 on 2021-01-29 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OUC', '0039_auto_20210124_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrank',
            name='courses_info',
            field=models.TextField(default='-', verbose_name='课程信息'),
        ),
        migrations.AddField(
            model_name='studentrank',
            name='exclude_courses',
            field=models.CharField(default='-', max_length=256, verbose_name='不参与排名的科目'),
        ),
    ]
