# Generated by Django 2.2.6 on 2021-01-24 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OUC', '0022_merge_20210107_1559'),
        ('OUC', '0039_auto_20210124_2138'),
    ]

    operations = [
    ]
