# Generated by Django 2.2.6 on 2021-01-29 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OUC', '0040_auto_20210129_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrank',
            name='courses_name',
            field=models.CharField(default='-', max_length=1024, verbose_name='课程名称'),
        ),
    ]
