# Generated by Django 2.2.6 on 2021-01-29 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OUC', '0040_merge_20210124_2215'),
        ('OUC', '0041_studentrank_courses_name'),
    ]

    operations = [
    ]
