# Generated by Django 2.2.6 on 2021-02-01 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OUC', '0042_merge_20210129_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swiper',
            name='image',
            field=models.ImageField(upload_to='upload_image/'),
        ),
    ]
