# Generated by Django 2.2.6 on 2021-02-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OUC', '0046_studentinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='img_url',
            field=models.CharField(default='-', max_length=65, verbose_name='个人照片'),
        ),
    ]
