# Generated by Django 2.2.6 on 2021-03-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OUC', '0047_studentinfo_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrank',
            name='courses_type',
            field=models.CharField(default='-', max_length=1024, verbose_name='课程类型'),
        ),
    ]
