# Generated by Django 2.2.6 on 2021-04-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OUC', '0048_studentrank_courses_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPProxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(default='-', max_length=50, verbose_name='ip')),
                ('get_ip_time', models.CharField(default='-', max_length=20, verbose_name='获取时间')),
                ('rest_time', models.IntegerField(default=298, max_length=10, verbose_name='剩余时间')),
                ('force_update', models.IntegerField(default=0, verbose_name='是否强制更新(1为强制，0为没有)')),
            ],
        ),
        migrations.AlterField(
            model_name='studentrank',
            name='exclude_courses',
            field=models.CharField(default='-', max_length=256, verbose_name='不参与排名的课程名称及类型'),
        ),
    ]
