# Generated by Django 2.2.6 on 2021-04-02 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OUC', '0049_auto_20210402_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipproxy',
            name='ip',
        ),
        migrations.AddField(
            model_name='ipproxy',
            name='proxy_ip',
            field=models.CharField(default='-', max_length=50, verbose_name='代理ip'),
        ),
    ]
