# Generated by Django 2.2.6 on 2021-04-02 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OUC', '0050_auto_20210402_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipproxy',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='最新获取日期'),
        ),
    ]
