# Generated by Django 2.2.6 on 2021-04-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OUC', '0051_ipproxy_update_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DreamOUCProfession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession_name', models.CharField(default='-', max_length=30, verbose_name='专业名称')),
                ('profession_material_title', models.CharField(default='-', max_length=20, verbose_name='资料及经验名称(10个字左右)')),
                ('profession_material_url', models.CharField(default='-', max_length=100, verbose_name='资料及经验地址')),
                ('open_course_title', models.CharField(default='-', max_length=20, verbose_name='公开课名称')),
                ('open_course_url', models.CharField(default='-', max_length=100, verbose_name='公开课地址')),
                ('taobao_key', models.CharField(default='-', max_length=100, verbose_name='淘口令')),
                ('update_intro', models.CharField(default='-', max_length=10, verbose_name='上新说明(不超过4个字)')),
                ('profession_material_description', models.TextField(default='-', verbose_name='其它说明')),
            ],
        ),
    ]
