# Generated by Django 2.2.6 on 2021-04-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OUC', '0052_dreamoucprofession'),
    ]

    operations = [
        migrations.AddField(
            model_name='dreamoucprofession',
            name='department_name',
            field=models.CharField(default='信息科学与工程学院', max_length=30, verbose_name='学院名称'),
        ),
        migrations.AlterField(
            model_name='dreamoucprofession',
            name='profession_material_url',
            field=models.CharField(default='-', max_length=100, verbose_name='资料及经验地址(微信文章跳转)'),
        ),
    ]
