# Generated by Django 2.2.6 on 2021-04-27 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OUC', '0054_auto_20210426_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='DreamOUCNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(default='-', max_length=30, verbose_name='标题')),
                ('news_url', models.CharField(default='-', max_length=100, verbose_name='内容地址')),
                ('news_tag', models.CharField(default='-', max_length=30, verbose_name='标签(#分割开，总共不超过12个字)')),
                ('news_is_top', models.SmallIntegerField(default=0, verbose_name='是否置顶（1为置顶，0为没有）')),
                ('news_top_val', models.SmallIntegerField(default=0, verbose_name='置顶优先级，数字越大越靠前')),
                ('published_time', models.DateTimeField(verbose_name='发布时间')),
                ('modified_time', models.DateTimeField(verbose_name='修改时间')),
                ('news_attention', models.IntegerField(default=10, max_length=10, verbose_name='查看次数')),
                ('news_hot_val', models.IntegerField(default=0, max_length=10, verbose_name='热度值')),
            ],
            options={
                'ordering': ('-published_time',),
            },
        ),
    ]
