# Generated by Django 2.2.6 on 2021-04-27 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OUC', '0055_dreamoucnews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dreamoucnews',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dreamoucnews',
            name='modified_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
    ]
