# Generated by Django 2.2.6 on 2021-04-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OUC', '0056_auto_20210427_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dreamoucnews',
            name='news_title',
            field=models.CharField(default='-', max_length=50, verbose_name='标题'),
        ),
    ]
