# Generated by Django 2.2.6 on 2021-04-28 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OUC', '0057_auto_20210427_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dreamoucnews',
            name='modified_time',
            field=models.DateTimeField(verbose_name='修改时间'),
        ),
    ]
