# Generated by Django 2.2.6 on 2021-10-10 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OUC', '0059_config_is_open_score_rank_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='is_open_score_rank_update',
            field=models.IntegerField(default=1, verbose_name='是否允许学生更新成绩排名的成绩(0:不开启,1:开启,2:只开启管理员的)'),
        ),
    ]
