# Generated by Django 2.2.6 on 2021-10-10 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OUC', '0060_auto_20211010_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='config',
            old_name='is_open_score_rank_update',
            new_name='is_open_rank_score_update',
        ),
    ]
