# Generated by Django 2.2.6 on 2022-01-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OUC', '0064_auto_20220123_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='extra',
            field=models.TextField(default='-', verbose_name='其它信息'),
        ),
    ]
